In [1]:
import cell2mol
import numpy as np

In [2]:
infopath = "BACZUB/BACZUB.info"

In [3]:
from cell2mol.read_write import readinfo
from cell2mol.classes import cell
from cell2mol.cell_reconstruction import classify_fragments, fragments_reconstruct
from cell2mol.charge_assignment import get_protonation_states_specie, balance_charge, get_list_of_charges_to_try, get_charge

In [4]:
name ="BACZUB"

In [5]:
debug=2

In [6]:
print(f"INITIATING cell object from input") 

# Reads reference molecules from info file, as well as labels and coordinates
labels, pos, ref_labels, ref_fracs, cellvec, cellparam = readinfo(infopath)
# Initiates cell
newcell = cell(name, labels, pos, cellvec, cellparam)
# # Loads the reference molecules and checks_missing_H
# # TODO : reconstruct the unit cell without using reference molecules
# # TODO : reconstruct the unit cell using (only reconstruction of) reference molecules and Space group
newcell.get_reference_molecules(ref_labels, ref_fracs, debug=debug) 
newcell.assess_errors()
# newcell.save(ref_cell_fname)
# ######################
# ### CALLS CELL2MOL ###
# ######################
# print(f"ENTERING cell2mol with debug={debug}")
# cell = cell2mol(newcell, reconstruction=True, charge_assignment=True, spin_assignment=True, debug=debug)
# cell.assess_errors()
# cell.save(cell_fname)

INITIATING cell object from input
MOLECULE.SPLIT COMPLEX: labels=['Hg', 'Fe', 'Cl', 'C', 'H', 'C', 'H', 'C', 'H', 'C', 'H', 'C', 'H', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'C', 'H']
MOLECULE.SPLIT COMPLEX: metal_idx=[0, 1]
MOLECULE.SPLIT COMPLEX: rest_idx=[2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]
SPLIT COMPLEX: rest labels: ['Cl', 'C', 'H', 'C', 'H', 'C', 'H', 'C', 'H', 'C', 'H', 'C', 'C', 'H', 'C', 'H', 'C', 'H', 'C', 'H']
SPLIT COMPLEX: rest coord: [[-0.3928769966037601, 2.3016163714687834, 7.603055514033566], [1.088207063968434, 4.309352587547709, 1.5686258268701916], [0.7532516276954522, 5.168808941441503, 1.697896237810325], [1.0397715909633676, 3.638400052685908, 0.36499880736037693], [0.6781788850937274, 3.946031481417394, -0.4334360837404476], [1.6288999872619745, 2.4157695326489255, 0.5757421663720231], [1.7526494162892954, 1.7496592112398208, -0.06517835845721018], [2.047083955789577, 2.334447308344994, 1.9879399329449103], [2.465130185355504, 1.62

In [7]:
mol = newcell.refmoleclist[0]
print(mol)

------------- Cell2mol MOLECULE Object --------------
 Version                      = 0.1
 Type                         = specie
 Sub-Type                     = molecule
 Number of Atoms              = 22
 Formula                      = H9-C10-Cl-Fe-Hg
 Has Adjacency Matrix         = YES
 Number of Ligands            = 3
 Number of Metals             = 2
---------------------------------------------------



In [8]:
lig = mol.ligands[0]
print(lig)

------------- Cell2mol LIGAND Object --------------
 Version                      = 0.1
 Type                         = specie
 Sub-Type                     = ligand
 Number of Atoms              = 10
 Formula                      = H5-C5
 Has Adjacency Matrix         = YES
 Number of Groups             = 1
---------------------------------------------------



In [9]:
for lig in mol.ligands:
    for gr in lig.groups:
        print(gr) 

------------- Cell2mol GROUP Object --------------
 Version                      = 0.1
 Type                         = specie
 Sub-Type                     = group
 Number of Atoms              = 5
 Formula                      = C5
 Has Adjacency Matrix         = YES
 Number of Metals             = 1
---------------------------------------------------

------------- Cell2mol GROUP Object --------------
 Version                      = 0.1
 Type                         = specie
 Sub-Type                     = group
 Number of Atoms              = 5
 Formula                      = C5
 Has Adjacency Matrix         = YES
 Number of Metals             = 2
---------------------------------------------------

------------- Cell2mol GROUP Object --------------
 Version                      = 0.1
 Type                         = specie
 Sub-Type                     = group
 Number of Atoms              = 1
 Formula                      = Cl
 Has Adjacency Matrix         = YES
 Number of Metals  

In [10]:
newcell.assess_errors()

In [11]:
newcell.has_isolated_H

False

In [12]:
for ref in newcell.refmoleclist:
    print(ref)
    if len(ref.ligands) > 0:
        print(ref.ligands)
        print(ref.metals)

------------- Cell2mol MOLECULE Object --------------
 Version                      = 0.1
 Type                         = specie
 Sub-Type                     = molecule
 Number of Atoms              = 22
 Formula                      = H9-C10-Cl-Fe-Hg
 Has Adjacency Matrix         = YES
 Number of Ligands            = 3
 Number of Metals             = 2
---------------------------------------------------

[------------- Cell2mol LIGAND Object --------------
 Version                      = 0.1
 Type                         = specie
 Sub-Type                     = ligand
 Number of Atoms              = 10
 Formula                      = H5-C5
 Has Adjacency Matrix         = YES
 Number of Groups             = 1
---------------------------------------------------
, ------------- Cell2mol LIGAND Object --------------
 Version                      = 0.1
 Type                         = specie
 Sub-Type                     = ligand
 Number of Atoms              = 9
 Formula                  

In [13]:
debug=1

In [14]:
newcell.check_missing_H(debug=debug)                                     

False

In [15]:
newcell.has_missing_H

False

In [16]:
newcell.reconstruct(debug=debug) 

SPECIE.INHERIT. found self in parent with indices=[1]
SPECIE.INHERIT: parent data:
parent.labels=['Hg', 'Cl']
parent.madjmat=array([[0, 1],
       [1, 0]])
parent.madjnum=array([1, 1])
parent.adjmat=array([[0, 1],
       [1, 0]])
parent.adjnum=array([1, 1])
SPECIE.INHERIT: self data:
self.labels=['Cl']
self.madjmat=array([[0]], dtype=object)
self.madjnum=array([1])
self.adjmat=array([[0]], dtype=object)
self.adjnum=array([1])
SPECIE.INHERIT. found self in parent with indices=[1, 2, 3, 4, 5, 6, 7, 8]
SPECIE.INHERIT: parent data:
parent.labels=['Fe', 'C', 'H', 'C', 'C', 'C', 'H', 'C', 'H']
parent.madjmat=array([[0, 1, 0, 1, 1, 1, 0, 1, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])
parent.madjnum=array([5, 1, 0, 1, 1, 1, 0, 1, 0])
parent.adjmat=a

[------------- Cell2mol MOLECULE Object --------------
  Version                      = 0.1
  Type                         = specie
  Sub-Type                     = molecule
  Number of Atoms              = 8
  Formula                      = Cl6-Hg2
  Has Adjacency Matrix         = YES
  Number of Ligands            = 6
  Number of Metals             = 2
 ---------------------------------------------------,
 ------------- Cell2mol MOLECULE Object --------------
  Version                      = 0.1
  Type                         = specie
  Sub-Type                     = molecule
  Number of Atoms              = 22
  Formula                      = H9-C10-Cl-Fe-Hg
  Has Adjacency Matrix         = YES
  Number of Ligands            = 3
  Number of Metals             = 2
 ---------------------------------------------------,
 ------------- Cell2mol MOLECULE Object --------------
  Version                      = 0.1
  Type                         = specie
  Sub-Type                     = mole

In [17]:
newcell.error_reconstruction

False

In [18]:
newcell.is_fragmented

False

In [19]:
newcell.get_unique_species(debug=0)

[------------- Cell2mol LIGAND Object --------------
  Version                      = 0.1
  Type                         = specie
  Sub-Type                     = ligand
  Number of Atoms              = 1
  Formula                      = Cl
  Has Adjacency Matrix         = YES
  Number of Groups             = 1
 ---------------------------------------------------,
 ------------- Cell2mol METAL Object --------------
  Version                      = 0.1
  Type                         = atom
  Sub-Type                     = metal
  Label                        = Hg
  Atomic Number                = 80
  Index in Molecule            = 0
  Metal Adjacency (mconnec)    = 4
  Regular Adjacencies (connec) = 4
  Coordination Sphere Formula  = Cl4
 ----------------------------------------------------,
 ------------- Cell2mol LIGAND Object --------------
  Version                      = 0.1
  Type                         = specie
  Sub-Type                     = ligand
  Number of Atoms           

In [20]:
selected_cs = []
for idx, spec in enumerate(newcell.unique_species):
    spec.get_possible_cs()
    if spec.subtype != "metal":
        selected_cs.append(list([cs.corr_total_charge for cs in spec.possible_cs]))
    else :
        selected_cs.append(spec.possible_cs)   
print(selected_cs)

ADD_ATOM: Metalist length 1
ADD_ATOM: Ligand Atoms 1
ADD_ATOM: site= 0
ADD_ATOM: evaluating apos=array([ 2.7576338, -3.8316994,  5.1099833]) and tgt.coord=[3.3561142, -1.7460605999999999, 4.0823379]
ADD_ATOM: received tmpconnec[posadded]=1
ADD_ATOM: Chosen Metal index None. H is added at site 0
protonation_states=[------------- Cell2mol Protonation ----------------
 Status                          = True
 Labels                          = ['Cl']
 Atoms added in positions        = [0]
 Atoms blocked (no atoms added)  = [1]
---------------------------------------------------
]
	Atom 0 : C 	Metal : Hg 	distance : 2.042 	thres : 2.501
	Atom 1 : C 	Metal : Fe 	distance : 2.051 	thres : 2.501
	Atom 2 : C 	Metal : Fe 	distance : 2.081 	thres : 2.501
	Atom 3 : C 	Metal : Fe 	distance : 2.068 	thres : 2.501
	Atom 4 : C 	Metal : Fe 	distance : 2.077 	thres : 2.501
ratio_list=[0.816, 0.82, 0.832, 0.827, 0.83] std_dev=0.006
protonation_states=[------------- Cell2mol Protonation ----------------
 S

In [21]:
for idx, spec in enumerate(newcell.unique_species):
    print(spec.possible_cs)

[------------- Cell2mol Charge State ---------------
 Status                          = True
 Smiles                          = [Cl-]
 Charge Tried                    = -1
 Uncorrected Total Charge        = -1
 Corrected Total Charge          = -1
 Corrected Absolute Total Charge = 1
 Corrected Is Zwitterion?        = False
---------------------------------------------------
]
[2]
[------------- Cell2mol Charge State ---------------
 Status                          = True
 Smiles                          = [H]C1=[C-]C([H])([H])C([H])=C1[H]
 Charge Tried                    = -1
 Uncorrected Total Charge        = -1
 Corrected Total Charge          = -2
 Corrected Absolute Total Charge = 2
 Corrected Is Zwitterion?        = False
---------------------------------------------------
]
[------------- Cell2mol Charge State ---------------
 Status                          = True
 Smiles                          = [H]C1=C([H])C([H])([H])C([H])=C1[H]
 Charge Tried                    = 0
 Uncorr

In [22]:
final_charge_distribution = balance_charge(newcell.unique_indices, newcell.unique_species, debug=2)

BALANCE: iterlist [[-1], [2], [-2], [-1], [2], [2, 3, 0]]
BALANCE: unique_indices [0, 0, 0, 0, 0, 0, 1, 1, 2, 3, 0, 4, 5, 2, 3, 0, 4, 5]
BALANCE: tmpdistr [(-1, 2, -2, -1, 2, 2), (-1, 2, -2, -1, 2, 3), (-1, 2, -2, -1, 2, 0)]
BALANCE: alldistr added: [-1, -1, -1, -1, -1, -1, 2, 2, -2, -1, -1, 2, 2, -2, -1, -1, 2, 2]
d=[-1, -1, -1, -1, -1, -1, 2, 2, -2, -1, -1, 2, 2, -2, -1, -1, 2, 2]
BALANCE: alldistr added: [-1, -1, -1, -1, -1, -1, 2, 2, -2, -1, -1, 2, 3, -2, -1, -1, 2, 3]
d=[-1, -1, -1, -1, -1, -1, 2, 2, -2, -1, -1, 2, 2, -2, -1, -1, 2, 2]
d=[-1, -1, -1, -1, -1, -1, 2, 2, -2, -1, -1, 2, 3, -2, -1, -1, 2, 3]
BALANCE: alldistr added: [-1, -1, -1, -1, -1, -1, 2, 2, -2, -1, -1, 2, 0, -2, -1, -1, 2, 0]
d=[-1, -1, -1, -1, -1, -1, 2, 2, -2, -1, -1, 2, 2, -2, -1, -1, 2, 2]
d=[-1, -1, -1, -1, -1, -1, 2, 2, -2, -1, -1, 2, 3, -2, -1, -1, 2, 3]
d=[-1, -1, -1, -1, -1, -1, 2, 2, -2, -1, -1, 2, 0, -2, -1, -1, 2, 0]


In [23]:
final_charge_distribution

[[-1, -1, -1, -1, -1, -1, 2, 2, -2, -1, -1, 2, 3, -2, -1, -1, 2, 3]]

In [24]:
from cell2mol.charge_assignment import prepare_mols
moleclist, error_prepare_mols = prepare_mols(newcell.moleclist, newcell.unique_indices, newcell.unique_species, selected_cs, final_charge_distribution[0], debug=2)

PREPARE: Molecule 0 has 6 ligands

PREPARE: Doing Ligand 0 with unique_index: 0
PREPARE: Ligand 
------------- Cell2mol LIGAND Object --------------
 Version                      = 0.1
 Type                         = specie
 Sub-Type                     = ligand
 Number of Atoms              = 1
 Formula                      = Cl
 Has Adjacency Matrix         = YES
 Number of Groups             = 1
---------------------------------------------------

PREPARE: Match with unique specie 
------------- Cell2mol LIGAND Object --------------
 Version                      = 0.1
 Type                         = specie
 Sub-Type                     = ligand
 Number of Atoms              = 1
 Formula                      = Cl
 Has Adjacency Matrix         = YES
 Number of Groups             = 1
---------------------------------------------------

PREPARE: Unique Specie has poscharges: 
[------------- Cell2mol Charge State ---------------
 Status                          = True
 Smiles            

ArgumentError: Python argument types in
    Atom.__init__(Atom, numpy.int64)
did not match C++ signature:
    __init__(_object*, unsigned int)
    __init__(_object*, RDKit::Atom)
    __init__(_object*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>)

In [25]:
for mol in newcell.moleclist:
    print(mol)

------------- Cell2mol MOLECULE Object --------------
 Version                      = 0.1
 Type                         = specie
 Sub-Type                     = molecule
 Number of Atoms              = 8
 Formula                      = Cl6-Hg2
 Has Adjacency Matrix         = YES
 Total Charge                 = -2
 SMILES                       = ['[Cl-]', '[Cl-]', '[Cl-]', '[Cl-]', '[Cl-]', '[Cl-]']
 Number of Ligands            = 6
 Number of Metals             = 2
---------------------------------------------------

------------- Cell2mol MOLECULE Object --------------
 Version                      = 0.1
 Type                         = specie
 Sub-Type                     = molecule
 Number of Atoms              = 22
 Formula                      = H9-C10-Cl-Fe-Hg
 Has Adjacency Matrix         = YES
 Number of Ligands            = 3
 Number of Metals             = 2
---------------------------------------------------

------------- Cell2mol MOLECULE Object --------------
 Version     

In [44]:
mol = newcell.moleclist[1]
for lig in mol.ligands:
    print(lig)

------------- Cell2mol LIGAND Object --------------
 Version                      = 0.1
 Type                         = specie
 Sub-Type                     = ligand
 Number of Atoms              = 9
 Formula                      = H4-C5
 Has Adjacency Matrix         = YES
 Number of Groups             = 1
---------------------------------------------------

------------- Cell2mol LIGAND Object --------------
 Version                      = 0.1
 Type                         = specie
 Sub-Type                     = ligand
 Number of Atoms              = 10
 Formula                      = H5-C5
 Has Adjacency Matrix         = YES
 Number of Groups             = 1
---------------------------------------------------

------------- Cell2mol LIGAND Object --------------
 Version                      = 0.1
 Type                         = specie
 Sub-Type                     = ligand
 Number of Atoms              = 1
 Formula                      = Cl
 Has Adjacency Matrix         = YES
 Numbe

In [45]:
lig = mol.ligands[0]
print(lig)

------------- Cell2mol LIGAND Object --------------
 Version                      = 0.1
 Type                         = specie
 Sub-Type                     = ligand
 Number of Atoms              = 9
 Formula                      = H4-C5
 Has Adjacency Matrix         = YES
 Number of Groups             = 1
---------------------------------------------------



In [46]:
cs = lig.possible_cs[0]
print(cs)

------------- Cell2mol Charge State ---------------
 Status                          = True
 Smiles                          = [H]C1=[C-]C([H])([H])C([H])=C1[H]
 Charge Tried                    = -1
 Uncorrected Total Charge        = -1
 Corrected Total Charge          = -2
 Corrected Absolute Total Charge = 2
 Corrected Is Zwitterion?        = False
---------------------------------------------------



In [56]:
prot = cs.protonation
print(prot)
print(prot.natoms)
print(prot.added_atoms)
print(prot.atnums)
print(prot.coords)
print(prot.adjmat)
#from cell2mol.connectivity import get_adjmatrix
#status, adjmat, adjnum = get_adjmatrix(prot.labels, prot.coords, prot.cov_factor, prot.radii)
#print("")
#print(adjmat)
#print(adjmat == prot.adjmat)

------------- Cell2mol Protonation ----------------
 Status                          = True
 Labels                          = ['C', 'C', 'H', 'C', 'H', 'C', 'H', 'C', 'H', 'H']
 Atoms added in positions        = [0, 1, 0, 0, 0, 0, 0, 0, 0]
 Atoms blocked (no atoms added)  = [0, 1, 0, 1, 0, 1, 0, 1, 0]
---------------------------------------------------

10
1
[6, 6, 1, 6, 1, 6, 1, 6, 1, 1]
[array([6.1022008, 2.0607668, 3.3610307]), array([5.5104028, 3.0110239, 2.5441286]), array([5.2421926, 3.8561355, 2.8254818]), array([5.3684013, 2.5137605, 1.2025407]), array([5.001188 , 2.9553237, 0.4714568]), array([5.8997816, 1.2250349, 1.2351299]), array([5.9443431, 0.6468013, 0.5073049]), array([6.3650269, 0.9240044, 2.5495601]), array([6.7663014, 0.1315989, 2.8243955]), array([6.37867421, 2.80753947, 2.18901936])]
[[0 1 0 0 0 0 0 1 0 0]
 [1 0 1 1 0 0 0 0 0 1]
 [0 1 0 0 0 0 0 0 0 0]
 [0 1 0 0 1 1 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 1 1 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [1 0 0 0 0 1 0 0 1 0]

In [48]:
from cell2mol.xyz2mol import xyz2mol
target_charge = cs.corr_total_charge
#new_cs = get_charge(target_charge, prot, allow=cs.allow, debug=2)
mols = xyz2mol(prot.atnums,prot.coords,prot.adjmat,prot.cov_factor,charge=target_charge,use_graph=True,allow_charged_fragments=cs.allow,embed_chiral=True,use_huckel=False)

XYZ2MOL.PROTO_MOL: doing atoms[i]=6


ArgumentError: Python argument types in
    Atom.__init__(Atom, numpy.int64)
did not match C++ signature:
    __init__(_object*, unsigned int)
    __init__(_object*, RDKit::Atom)
    __init__(_object*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>)