In [1]:
import sys
sys.path.append("/Users/sergivela/Documents/Programes/cell2mol_dev/cell2mol")

import cell2mol
from cell2mol.read_write import *
from cell2mol.classes import *

In [2]:
debug = 2
infopath = "/Users/sergivela/Documents/Programes/cell2mol_dev/cell2mol/cell2mol/test/infodata/AFUGIS.info"

In [3]:
labels, pos, ref_labels, ref_fracs, cellvec, cellparam = readinfo(infopath)
newcell = cell("name", labels, pos, cellvec, cellparam)

In [4]:
newcell.get_reference_molecules(ref_labels, ref_fracs, debug=debug)

SPECIE.SET_ATOMS: creating atom for label Fe
SPECIE.SET_ATOMS: ismetal=True
SPECIE.SET_ATOMS: added atom to specie: 
------------- Cell2mol METAL Object --------------
 Version                      = 0.1
 Type                         = atom
 Sub-Type                    = metal
 Label                        = Fe
 Atomic Number                = 26
 Index in Parent (molecule)     = 0
----------------------------------------------------

SPECIE.SET_ATOMS: creating atom for label N
SPECIE.SET_ATOMS: ismetal=False
SPECIE.SET_ATOMS: added atom to specie: 
------------- Cell2mol ATOM Object ----------------
 Version                      = 0.1
 Type                         = atom
 Label                        = N
 Atomic Number                = 7
 Index in Parent (molecule)     = 1
----------------------------------------------------

SPECIE.SET_ATOMS: creating atom for label N
SPECIE.SET_ATOMS: ismetal=False
SPECIE.SET_ATOMS: added atom to specie: 
------------- Cell2mol ATOM Object ----------

[------------- Cell2mol MOLECULE Object --------------
  Version               = 0.1
  Type                  = specie
  Sub-Type               = molecule
  Number of Atoms       = 115
  Formula               = H68-C42-N4-Fe
  Has Adjacency Matrix  = YES
  # Ligands             = 2
  # Metals              = 1
 ---------------------------------------------------]

In [5]:
for ref in newcell.refmoleclist:
    if ref.iscomplex: ref.split_complex()
    print(ref)

------------- Cell2mol MOLECULE Object --------------
 Version               = 0.1
 Type                  = specie
 Sub-Type               = molecule
 Number of Atoms       = 115
 Formula               = H68-C42-N4-Fe
 Has Adjacency Matrix  = YES
 # Ligands             = 2
 # Metals              = 1
---------------------------------------------------



In [6]:
for ref in newcell.refmoleclist:
    for lig in ref.ligands:
        lig.split_ligand(debug=debug)
        print(lig.groups)

LIGAND.SPLIT_LIGAND: self.indices=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]
LIGAND.SPLIT_LIGAND: conn_idx=[0, 1, 2]
labels=['N', 'N', 'C'] 3
indices=None
LIGAND.SPLIT_LIGAND: block=[0, 1, 2]
LIGAND.SPLIT_LIGAND: gr_indices=[0, 1, 2]
[------------- Cell2mol GROUP Object --------------
 Version               = 0.1
 Type                  = specie
 Sub-Type               = group
 Number of Atoms       = 3
 Formula               = C-N2
 Has Adjacency Matrix  = NO 
 Has Parent            = YES
---------------------------------------------------
]
LIGAND.SPLIT_LIGAND: self.indices=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89]
LIGAND.SPLIT_LIGAND: co

In [7]:
for ref in newcell.refmoleclist:
    for lig in ref.ligands:
        print(lig)
        for gr in lig.groups:
            print(gr)

------------- Cell2mol LIGAND Object --------------
 Version               = 0.1
 Type                  = specie
 Sub-Type               = ligand
 Number of Atoms       = 24
 Formula               = H15-C7-N2
 Has Adjacency Matrix  = NO 
 Has Parent            = YES
 # Groups              = 1
---------------------------------------------------

------------- Cell2mol GROUP Object --------------
 Version               = 0.1
 Type                  = specie
 Sub-Type               = group
 Number of Atoms       = 3
 Formula               = C-N2
 Has Adjacency Matrix  = NO 
 Has Parent            = YES
---------------------------------------------------

------------- Cell2mol LIGAND Object --------------
 Version               = 0.1
 Type                  = specie
 Sub-Type               = ligand
 Number of Atoms       = 90
 Formula               = H53-C35-N2
 Has Adjacency Matrix  = NO 
 Has Parent            = YES
 # Groups              = 2
----------------------------------------------

In [8]:
for ref in newcell.refmoleclist:
    for lig in ref.ligands:
        lig.get_denticity(debug=debug)

LIGAND.Get_denticity: checking connectivity of ligand H15-C7-N2
LIGAND.Get_denticity: initial connectivity is 3
LIGAND.Get_denticity: checking denticity of group 
------------- Cell2mol GROUP Object --------------
 Version               = 0.1
 Type                  = specie
 Sub-Type               = group
 Number of Atoms       = 3
 Formula               = C-N2
 Has Adjacency Matrix  = NO 
 Has Parent            = YES
---------------------------------------------------

Entering COORD_CORR_NONHAPTIC:
	connectivity=1 in atom idx=0, label=N
	connectivity verified for atom 0 with label N
	connectivity=1 in atom idx=1, label=N
	connectivity verified for atom 1 with label N
	connectivity=1 in atom idx=2, label=C
	corrected mconnec of atom 2 with label C
ATOM.RESET_MCONN: resetting mconnec for atom self.label='C' with self.parent_index=3
ATOM.RESET_MCONN: updating ligand atoms and madjnum
ATOM.RESET_MCONN: initial self.parent.madjnum=[1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [9]:
for ref in newcell.refmoleclist:
    print(ref.ligands)

[------------- Cell2mol LIGAND Object --------------
 Version               = 0.1
 Type                  = specie
 Sub-Type               = ligand
 Number of Atoms       = 24
 Formula               = H15-C7-N2
 Has Adjacency Matrix  = NO 
 Has Parent            = YES
 # Groups              = 1
---------------------------------------------------
, ------------- Cell2mol LIGAND Object --------------
 Version               = 0.1
 Type                  = specie
 Sub-Type               = ligand
 Number of Atoms       = 90
 Formula               = H53-C35-N2
 Has Adjacency Matrix  = NO 
 Has Parent            = YES
 # Groups              = 2
---------------------------------------------------
]


In [10]:
newcell.reconstruct(debug=debug)

CLASSIFY FRAGMENTS, preparing block ------------- Cell2mol MOLECULE Object --------------
 Version               = 0.1
 Type                  = specie
 Sub-Type               = molecule
 Number of Atoms       = 4
 Formula               = H3-C
 Has Adjacency Matrix  = YES
 Has Parent            = YES
---------------------------------------------------

CLASSIFY FRAGMENTS, preparing block ------------- Cell2mol MOLECULE Object --------------
 Version               = 0.1
 Type                  = specie
 Sub-Type               = molecule
 Number of Atoms       = 4
 Formula               = H3-C
 Has Adjacency Matrix  = YES
 Has Parent            = YES
---------------------------------------------------

CLASSIFY FRAGMENTS, preparing block ------------- Cell2mol MOLECULE Object --------------
 Version               = 0.1
 Type                  = specie
 Sub-Type               = molecule
 Number of Atoms       = 3
 Formula               = H2-C
 Has Adjacency Matrix  = YES
 Has Parent         

[]

In [11]:
moleclist = newcell.get_moleclist()

In [12]:
for b in moleclist:
    print(b.natoms, np.array(b.coord))
    compute_centroid(np.array(b.coord))
    print("done")
    b.get_centroid()

4 [[-1.1937221 -2.1865769 12.7667211]
 [-0.3117672 -1.7814696 12.9064746]
 [-1.4016727 -2.7846598 13.5149354]
 [-1.8724681 -1.4818892 12.7140174]]
done
4 [[ 5.7246437 11.1653886  2.0376774]
 [ 4.8426888 10.7602813  1.8979239]
 [ 5.9325943 11.7634715  1.2894631]
 [ 6.4033897 10.4607009  2.0903811]]
done
3 [[-1.1746916 -1.9618068 10.3109675]
 [-0.3397163 -1.4504087 10.3423528]
 [-1.935401  -1.3526957 10.4148944]]
done
2 [[ 2.4747013 -1.4929587  8.5501323]
 [ 3.0981737 -0.7860424  8.6679753]]
done
2 [[ 2.0562203 10.4717704  6.2542662]
 [ 1.4327479  9.7648541  6.1364232]]
done
4 [[5.510898  7.9858255 7.1215079]
 [4.8465157 7.2667646 7.1001895]
 [5.786693  8.2028764 6.2060039]
 [5.1200057 8.7795856 7.5413606]]
done
4 [[-0.9799764  0.9929862  7.6828907]
 [-0.3155941  1.7120471  7.704209 ]
 [-1.2557714  0.7759353  8.5983947]
 [-0.5890841  0.1992261  7.2630379]]
done
8 [[ 2.8326606 -2.0473122 10.9743526]
 [ 2.3795898 -0.7192609 11.5959893]
 [ 1.4107112 -0.7395424 11.739888 ]
 [ 2.6050304  0.01

In [ ]:
classify_fragments(moleclist, newcell.refmoleclist, debug=2)